version: 'staging'
replicaCount: 1

services:
  config-server:
    containerName: config-server
    image: ptn3001/spring-petclinic-config-server
    tag: "staging" # chỉ định tag staging nếu có
    port: 8888
  customers-service:
    containerName: customers-service
    image: ptn3001/spring-petclinic-customers-service
    tag: "staging"
    port: 8081
  discovery-server:
    containerName: discovery-server
    image: ptn3001/spring-petclinic-discovery-server
    tag: "staging"
    port: 8761
  visits-service:
    containerName: visits-service
    image: ptn3001/spring-petclinic-visits-service
    tag: "staging"
    port: 8082
  vets-service:
    containerName: vets-service
    image: ptn3001/spring-petclinic-vets-service
    tag: "staging"
    port: 8083
  genai-service:
    containerName: genai-service
    image: ptn3001/spring-petclinic-genai-service
    tag: "staging"
    port: 8084
  api-gateway:
    containerName: api-gateway
    image: ptn3001/spring-petclinic-api-gateway
    tag: "staging"
    port: 8080
  admin-server:
    containerName: admin-server
    image: ptn3001/spring-petclinic-admin-server
    tag: "staging"
    port: 9090

ingress:
  enabled: true
  host: staging.spring-petclinic.com  # hostname cho staging
